### ISSUE TITLE
wartosci do stalych

### ISSUE THREAD

**Issue by pwr-mszczepanik** [Ceglowa/SWiM_Lab_1#1]
https://github.com/Ceglowa/SWiM_Lab_1/blob/99505d482df1682eccdd07c1479ce956a27326cd/app/src/main/java/com/example/filipdratwiski/lab1_237999/BMIResult.java#L46

dla mnie to magiczna liczba mogles je wyjac do stalych (static final)

**Comment by Ceglowa** [comment]
Wszystkie magiczne liczby przerzucilem do stalych.
