### ISSUE TITLE
a gdzie test dla innych jednostek

### ISSUE THREAD

**Issue by pwr-mszczepanik** [Ceglowa/SWiM_Lab_1#2]
https://github.com/Ceglowa/SWiM_Lab_1/blob/99505d482df1682eccdd07c1479ce956a27326cd/app/src/test/java/com/example/filipdratwiski/lab1_237999/ExampleUnitTest.java#L19

czemu testy sa tylko dla danych metrycznych ?

**Comment by Ceglowa** [comment]
Dodałem nowe testy. Są też testy dla jednostek imperialnych.
