### ISSUE TITLE
logika w UI

### ISSUE THREAD

**Issue by pwr-mszczepanik** [Ceglowa/SWiM_Lab_1#3]
https://github.com/Ceglowa/SWiM_Lab_1/blob/99505d482df1682eccdd07c1479ce956a27326cd/app/src/main/java/com/example/filipdratwiski/lab1_237999/BMI.java#L33

przeliczanie jednostek to jest część logiki nie UI

**Comment by Ceglowa** [comment]
Poprawiono. Teraz konwertowanie jest w klasie BMICounter z dala od UI.
